name: Main

on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: ${{ github.event_name == 'merge_group' }}
        run: echo "Merge Group"

      - if: ${{ github.event_name == 'pull_request' }}
        run: echo "Pull Request"

      - run: cargo check --tests --benches --all-features
