name: Main

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo check --tests --benches --all-features
